baseURL = "https://your-domain.com/"
languageCode = "en"
title = "NodAlert Privacy Policy"
disableHugoGeneratorInject = true

[params]
  [params.privacy]
    last_updated = "2026-04-22"
    contact_email = "support@nodalert.app"
    app_name = "NodAlert"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Disable RSS
[rss]
  disable = true
